version: '3'

services:
  django:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DATABASE_URL=${DATABASE_URL}

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: sh -c "celery -A testkeycloak worker --loglevel=info & celery -A testkeycloak flower --broker=redis://redis:6379/0 --port=5555"
    volumes:
      - .:/usr/src/app
    ports:
      - "5555:5555"
    depends_on:
      - redis

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  celery-beat:
    build: .
    command: celery -A testkeycloak beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - postgres

volumes:
  postgres_data:
