"""
Django settings for testkeycloak project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-myb(f11sniua!rcdzj^8-*&qnp44g&1pvv2$emu^x46_url#$p"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    'myapp',
    "django_celery_beat",
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "testkeycloak.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "testkeycloak.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'keycloak',
        'USER': 'keycloak',
        'PASSWORD': 'password',
        'HOST': 'postgres',
        'PORT': '5432',
    }
}


LOGIN_REDIRECT_URL = '/admin/'
LOGIN_URL = 'keycloak_login'
KEYCLOAK_SERVER_URL = 'http://localhost:8080/auth/'
KEYCLOAK_REALM = 'master'
KEYCLOAK_CLIENT_ID = 'django-client'
KEYCLOAK_CLIENT_SECRET = 'MIICqTCCAZECBgGM+BoXyTANBgkqhkiG9w0BAQsFADAYMRYwFAYDVQQDDA1kamFuZ28tY2xpZW50MB4XDTI0MDExMTEwMzY0OFoXDTM0MDExMTEwMzgyOFowGDEWMBQGA1UEAwwNZGphbmdvLWNsaWVudDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMStJ30tGHOqY+72gk8cauS1RpIMHUU7qi2Bi5sLLoiRswGjKStctmg9Q15fswaBk0hVATvral3XbAc/2i7dRqNcC9mhVAi1lZKxjR1Fku8eUIMgDyKDmsARJcTexRxjMRno8AodhOmC3Yp0LpFucuwiUTEcoAzOaSEdfd+zEiVGftzviidzVsoorCm9YTLt7ehjZYPTKfoSP1xaUB9eWHU5pAcM+5j4XYpQPsC6kqm5Oq6m0ex2EGrdqj2TqJMdj4EdWyfYvayPRp7aKHvizoVK4HUSVG82QN3w/xlRPWhDuxEQf4qOJTlyE7bvC1Ywf4dJpt/4dr+GGEfXvaM+a0UCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAgc8G8/ByLfggw9VIzhiaasVG2gVZDgGlPka9mM1n86H6n8SqEXwZ48rmBCz2ljH+0QaIZAyVIueZ+rWwXj0fH7AB5DO4zuq6/EWeHfLSzpLTV8zuAo3aG/p6a7mhxiv6CnfbFAynCEdnufi0IlUKgD9UJ7G/dkRZRwAr1syAAvFEtu7iVfO5WyX0G8oRsVIiSyHVlNiP9MrqxIG2ZFBm/OTtUZzSfIPTEkAbYZSpEJUzyB3D6ccd+ssjaeYecBTShWzWPDfBLhD5/keouIMQoNirtLFTBokJqD98oYIuMTehYjpt2RGnqOLxfRRJFdkppWWZ0dzs/3G2cBYaaeCEiQ=='
KEYCLOAK_PROTOCOL = 'openid-connect'

CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
CELERY_BEAT_SCHEDULE = {
    'delete_old_webhooks_every_hour': {
        'task': 'myapp.tasks.delete_old_webhooks',
        'schedule': crontab(minute='*/1'),
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
